package com.bigeye.mycust.appdirect.enums;

public enum EventResultErrorMessageEnum {
		USER_ALREADY_EXISTS,
		USER_NOT_FOUND,
		ACCOUNT_NOT_FOUND,
		MAX_USERS_REACHED,
		UNAUTHORIZED,
		OPERATION_CANCELED,
		CONFIGURATION_ERROR,
		INVALID_RESPONSE,
		UNKNOWN_ERROR;
}
